-- ============================
-- DROPAR TABELAS E CONSTRAINTS
-- ============================

-- 1. Dropar tabela FEEDBACK (depende de CONSULTA)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_JPS_FEEDBACK CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    NULL;
END;
/

-- 2. Dropar tabela CONSULTA (depende de FUNCIONARIO, MEDICO, PACIENTE)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_JPS_CONSULTA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    NULL;
END;
/

-- 3. Dropar tabela FUNCIONARIO
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_JPS_FUNCIONARIO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    NULL;
END;
/

-- 4. Dropar tabela MEDICO
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_JPS_MEDICO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    NULL;
END;
/

-- 5. Dropar tabela PACIENTE
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE T_JPS_PACIENTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    NULL;
END;
/

-- ============================
-- DROPAR SEQUENCES
-- ============================

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PACIENTE';
EXCEPTION WHEN OTHERS THEN
    NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MEDICO';
EXCEPTION WHEN OTHERS THEN
    NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CONSULTA';
EXCEPTION WHEN OTHERS THEN
    NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FUNCIONARIO';
EXCEPTION WHEN OTHERS THEN
    NULL;
END;
/
