
CREATE TABLE T_JPS_CONSULTA
    (
     ID_CONSULTA    NUMBER (5)  NOT NULL ,
     DT_HR_CONSULTA DATE  NOT NULL ,
     ID_PACIENTE    NUMBER (5)  NOT NULL ,
     ID_MEDICO      NUMBER (5)  NOT NULL ,
     ID_FUNCIONARIO NUMBER (5)  NULL ,
     ST_CONSULTA    VARCHAR2 (30 CHAR)  NOT NULL
    )
;

ALTER TABLE T_JPS_CONSULTA
    ADD CONSTRAINT CK_ST_CONSULTA
    CHECK (ST_CONSULTA IN ('Confirmada', 'Em Andamento', 'Realizada'))
;

COMMENT ON COLUMN T_JPS_CONSULTA.ID_CONSULTA IS 'ID DA CONSULTA'
;

COMMENT ON COLUMN T_JPS_CONSULTA.DT_HR_CONSULTA IS 'DATA E HORA DA CONSULTA'
;

COMMENT ON COLUMN T_JPS_CONSULTA.ST_CONSULTA IS 'STATUS CONSULTA (CONCLUIDO, EM ANDAMENTO OU CONFIRMADA)'
;

ALTER TABLE T_JPS_CONSULTA
    ADD CONSTRAINT T_JPS_CONSULTA_PK PRIMARY KEY ( ID_CONSULTA ) ;

CREATE TABLE T_JPS_FEEDBACK
    (
     ID_FEEDBACK NUMBER (5)  NOT NULL ,
     NT_FEEDBACK NUMBER (2,1)  NOT NULL ,
     DS_FEEDBACK VARCHAR2 (100 CHAR) ,
     ID_CONSULTA NUMBER (5)  NOT NULL
    )
;

ALTER TABLE T_JPS_FEEDBACK
    ADD CONSTRAINT CK_NOTA_FEEDBACK
    CHECK (NT_FEEDBACK IN (0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0))
;

COMMENT ON COLUMN T_JPS_FEEDBACK.NT_FEEDBACK IS 'NOTA DO FEEDBACK SENDO DE 0.0 A 5.0, EM INTERVALOS DE 0.5.
USAR CHECK CONSTRAINT'
;

COMMENT ON COLUMN T_JPS_FEEDBACK.DS_FEEDBACK IS 'DESCRICAO DO FEEDBACK/JUSTIFICATIVA DA NOTA'
;
CREATE UNIQUE INDEX T_JPS_FEEDBACK__IDX ON T_JPS_FEEDBACK
    (
     ID_CONSULTA ASC
    )
;

ALTER TABLE T_JPS_FEEDBACK
    ADD CONSTRAINT T_JPS_FEEDBACK_PK PRIMARY KEY ( ID_FEEDBACK ) ;


CREATE TABLE T_JPS_FUNCIONARIO
    (
     ID_FUNCIONARIO   NUMBER (5)  NOT NULL ,
     NM_FUNCIONARIO   VARCHAR2 (100 CHAR)  NOT NULL ,
     CPF_FUNCIONARIO  VARCHAR2 (11 CHAR)  NOT NULL ,
     TEL1_FUNCIONARIO VARCHAR2 (11 CHAR)  NOT NULL ,
     TEL2_FUNCIONARIO VARCHAR2 (11 CHAR) ,
     IDD_FUNCIONARIO  NUMBER (3)  NOT NULL ,
     EM_FUNCIONARIO   VARCHAR2 (320 CHAR)  NOT NULL
    )
;

COMMENT ON COLUMN T_JPS_FUNCIONARIO.ID_FUNCIONARIO IS 'ID FUNCIONARIO'
;

COMMENT ON COLUMN T_JPS_FUNCIONARIO.NM_FUNCIONARIO IS 'NOME DO FUNCIONARIO'
;

COMMENT ON COLUMN T_JPS_FUNCIONARIO.CPF_FUNCIONARIO IS 'CPF MEDICO 11 FUNCIONARIO'
;

COMMENT ON COLUMN T_JPS_FUNCIONARIO.TEL1_FUNCIONARIO IS 'TELEFONE 1 FUNCIONARIO'
;

COMMENT ON COLUMN T_JPS_FUNCIONARIO.TEL2_FUNCIONARIO IS 'TELEFONE 2 FUNCIONARIO'
;

COMMENT ON COLUMN T_JPS_FUNCIONARIO.IDD_FUNCIONARIO IS 'IDADE FUNCIONARIO'
;

COMMENT ON COLUMN T_JPS_FUNCIONARIO.EM_FUNCIONARIO IS 'EMAIL FUNCIONARIO'
;

ALTER TABLE T_JPS_FUNCIONARIO
    ADD CONSTRAINT T_JPS_FUNCIONARIO_PK PRIMARY KEY ( ID_FUNCIONARIO ) ;

ALTER TABLE T_JPS_FUNCIONARIO
    ADD CONSTRAINT UK_CPF_FUNCIONARIO UNIQUE ( CPF_FUNCIONARIO ) ;

ALTER TABLE T_JPS_FUNCIONARIO
    ADD CONSTRAINT UK_TEL1_FUNCIONARIO UNIQUE ( TEL1_FUNCIONARIO ) ;

ALTER TABLE T_JPS_FUNCIONARIO
    ADD CONSTRAINT UK_TEL2_FUNCIONARIO UNIQUE ( TEL2_FUNCIONARIO ) ;

CREATE TABLE T_JPS_MEDICO
    (
     ID_MEDICO   NUMBER (5)  NOT NULL ,
     NM_MEDICO   VARCHAR2 (100 CHAR)  NOT NULL ,
     CPF_MEDICO  VARCHAR2 (11 CHAR)  NOT NULL ,
     CRM_MEDICO  NUMBER (6)  NOT NULL ,
     TEL1_MEDICO VARCHAR2 (11 CHAR)  NOT NULL ,
     TEL2_MEDICO VARCHAR2 (11 CHAR) ,
     EM_MEDICO   VARCHAR2 (320 CHAR)  NOT NULL ,
     ESP_MEDICO  VARCHAR2 (30 CHAR)  NOT NULL ,
     IDD_MEDICO  NUMBER (3)  NOT NULL
    )
;

COMMENT ON COLUMN T_JPS_MEDICO.ID_MEDICO IS 'ID MEDICO'
;

COMMENT ON COLUMN T_JPS_MEDICO.NM_MEDICO IS 'NOME DO MEDICO'
;

COMMENT ON COLUMN T_JPS_MEDICO.CPF_MEDICO IS 'CPF MEDICO 11 DIGITOS'
;

COMMENT ON COLUMN T_JPS_MEDICO.CRM_MEDICO IS 'CRM DO MEDICO 6 DIGITOS'
;

COMMENT ON COLUMN T_JPS_MEDICO.TEL1_MEDICO IS 'TELEFONE 1 MEDICO'
;

COMMENT ON COLUMN T_JPS_MEDICO.TEL2_MEDICO IS 'TELEFONE 2 MEDICO'
;

COMMENT ON COLUMN T_JPS_MEDICO.EM_MEDICO IS 'EMAIL MEDICO'
;

COMMENT ON COLUMN T_JPS_MEDICO.ESP_MEDICO IS 'ESPECIALIDADE MEDICO'
;

COMMENT ON COLUMN T_JPS_MEDICO.IDD_MEDICO IS 'IDADE MEDICO'
;

ALTER TABLE T_JPS_MEDICO
    ADD CONSTRAINT T_JPS_MEDICO_PK PRIMARY KEY ( ID_MEDICO ) ;

ALTER TABLE T_JPS_MEDICO
    ADD CONSTRAINT UK_JPS_CPF_MEDICO UNIQUE ( CPF_MEDICO ) ;

ALTER TABLE T_JPS_MEDICO
    ADD CONSTRAINT UK_JPS_TEL1_MEDICO UNIQUE ( TEL1_MEDICO ) ;

ALTER TABLE T_JPS_MEDICO
    ADD CONSTRAINT UK_JPS_TEL2_MEDICO UNIQUE ( TEL2_MEDICO ) ;

ALTER TABLE T_JPS_MEDICO
    ADD CONSTRAINT UK_JPS_CRM_MEDICO UNIQUE ( CRM_MEDICO ) ;

CREATE TABLE T_JPS_PACIENTE
    (
     ID_PACIENTE   NUMBER (5)  NOT NULL ,
     NM_PACIENTE   VARCHAR2 (100 CHAR)  NOT NULL ,
     CPF_PACIENTE  VARCHAR2 (11 CHAR)  NOT NULL ,
     IDD_PACIENTE  NUMBER (3)  NOT NULL ,
     EM_PACIENTE   VARCHAR2 (320 CHAR)  NOT NULL ,
     TEL1_PACIENTE VARCHAR2 (11 CHAR)  NOT NULL ,
     TEL2_PACIENTE VARCHAR2 (11 CHAR)
    )
;

ALTER TABLE T_JPS_PACIENTE
    ADD CONSTRAINT CK_IDADE_PACIENTE
    CHECK (IDD_PACIENTE BETWEEN 1 AND 120)
;

COMMENT ON COLUMN T_JPS_PACIENTE.ID_PACIENTE IS 'ID PACIENTE'
;

COMMENT ON COLUMN T_JPS_PACIENTE.NM_PACIENTE IS 'NOME DO PACIENTE'
;

COMMENT ON COLUMN T_JPS_PACIENTE.CPF_PACIENTE IS 'CPF PACIENTE 11 DIGITOS'
;

COMMENT ON COLUMN T_JPS_PACIENTE.IDD_PACIENTE IS 'IDADE'
;

COMMENT ON COLUMN T_JPS_PACIENTE.EM_PACIENTE IS 'EMAIL PACIENTE'
;

ALTER TABLE T_JPS_PACIENTE
    ADD CONSTRAINT T_JPS_PACIENTE_PK PRIMARY KEY ( ID_PACIENTE ) ;

ALTER TABLE T_JPS_PACIENTE
    ADD CONSTRAINT UK_JPS_CPF_PACIENTE UNIQUE ( CPF_PACIENTE ) ;

ALTER TABLE T_JPS_PACIENTE
    ADD CONSTRAINT UK_JPS_EM_PACIENTE UNIQUE ( EM_PACIENTE ) ;

ALTER TABLE T_JPS_PACIENTE
    ADD CONSTRAINT UK_JPS_TEL1_PACIENTE UNIQUE ( TEL1_PACIENTE ) ;

ALTER TABLE T_JPS_PACIENTE
    ADD CONSTRAINT UK_JPS_TEL2_PACIENTE UNIQUE ( TEL2_PACIENTE ) ;

ALTER TABLE T_JPS_FEEDBACK
    ADD CONSTRAINT FK_JPS_CONSULTA_FEEDBACK FOREIGN KEY
    (
     ID_CONSULTA
    )
    REFERENCES T_JPS_CONSULTA
    (
     ID_CONSULTA
    )
;

ALTER TABLE T_JPS_CONSULTA
    ADD CONSTRAINT FK_JPS_FUNCIONARIO_CONSULTA FOREIGN KEY
    (
     ID_FUNCIONARIO
    )
    REFERENCES T_JPS_FUNCIONARIO
    (
     ID_FUNCIONARIO
    )
;

ALTER TABLE T_JPS_CONSULTA
    ADD CONSTRAINT FK_JPS_MEDICO_CONSULTA FOREIGN KEY
    (
     ID_MEDICO
    )
    REFERENCES T_JPS_MEDICO
    (
     ID_MEDICO
    )
;

ALTER TABLE T_JPS_CONSULTA
    ADD CONSTRAINT FK_JPS_PACIENTE_CONSULTA FOREIGN KEY
    (
     ID_PACIENTE
    )
    REFERENCES T_JPS_PACIENTE
    (
     ID_PACIENTE
    )
;

ALTER TABLE T_JPS_PACIENTE
    ADD PSWD_PACIENTE VARCHAR2(50 CHAR) NOT NULL;

ALTER TABLE T_JPS_FUNCIONARIO
    ADD PSWD_FUNCIONARIO VARCHAR2(50 CHAR) NOT NULL;

ALTER TABLE T_JPS_MEDICO
    ADD PSWD_MEDICO VARCHAR2(50 CHAR) NOT NULL;

ALTER TABLE T_JPS_PACIENTE
    ADD CONSTRAINT CK_PSWD_PACIENTE_LEN
    CHECK (LENGTH(PSWD_PACIENTE) >= 6);

ALTER TABLE T_JPS_MEDICO
    ADD CONSTRAINT CK_PSWD_MEDICO_LEN
    CHECK (LENGTH(PSWD_MEDICO) >= 6);

ALTER TABLE T_JPS_FUNCIONARIO
    ADD CONSTRAINT CK_PSWD_FUNCIONARIO_LEN
    CHECK (LENGTH(PSWD_FUNCIONARIO) >= 6);

CREATE SEQUENCE SEQ_PACIENTE
    START WITH 10000
    INCREMENT BY 1
    MAXVALUE 19999
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_MEDICO
    START WITH 10000
    INCREMENT BY 1
    MAXVALUE 19999
    NOCACHE
    NOCYCLE;


CREATE SEQUENCE SEQ_CONSULTA
    START WITH 10000
    INCREMENT BY 1
    MAXVALUE 19999
    NOCACHE
    NOCYCLE;


CREATE SEQUENCE SEQ_FUNCIONARIO
    START WITH 10000
    INCREMENT BY 1
    MAXVALUE 19999
    NOCACHE
    NOCYCLE;


-- Relatório do Resumo do Oracle SQL Developer Data Modeler:
--
-- CREATE TABLE                             5
-- CREATE INDEX                             1
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   0
-- WARNINGS                                 0